### ISSUE TITLE
/root/ebpf-firewall/go.mod:3: invalid go version '1.23.2': must match format 1.23报错

### ISSUE THREAD

**Issue by DR-lin-eng** [danger-dream/ebpf-firewall#2]
这个错误是因为 go.mod 文件中指定的 Go 版本格式不正确。Go 的版本格式要求是 1.x 或 1.x.x，而你的版本写成了 1.23.2，导致不符合格式要求。

解决方法：
打开 /root/ebpf-firewall/go.mod 文件。
找到文件中的 go 1.23.2 这一行，将其修改为 go 1.23，这样版本号将符合 Go 语言的标准格式。

**Comment by danger-dream** [comment]
go.mod由 `go mod init` 命令生成。

为保证向下兼容，晚些时候我会修复它(出差中...)。谢谢。

**Comment by LinkinStars** [comment]
@DR-lin-eng 首先并不是格式不正确，也没有这个说法 “go 1.23，这样版本号将_符合 Go 语言的标准格式。_” ，而是在高版本的 go 里面是支持这样写的。作者写了前置条件是：Go 1.23.2+，**所以用 1.23 的版本去编译就不会出现这个问题了哈**。并且提醒一下，即使改了这里，低版本编译还是可能会有其他问题，建议还是使用推荐版本。

**Comment by danger-dream** [comment]
fixed
