### ISSUE TITLE
[perf] the summary message is too big

### ISSUE THREAD

**Issue by nook4sh** [danger-dream/ebpf-firewall#4]
The summary message from the ws server becomes too large to load in the frontend. After the server runs for several hours or days, the message can grow to millions of lines in JSON format, causing the frontend to become very slow.

![image](https://github.com/user-attachments/assets/6439d949-ebca-4877-9d4c-f0d7f404aa1c)
![image](https://github.com/user-attachments/assets/6a16e5d5-289b-4e88-a0e1-9e4e0eab1b6a)

**Comment by danger-dream** [comment]
Yes, this issue will occur after running for a while, and it will be fixed in the next version

**Comment by danger-dream** [comment]
fixed
